### PR TITLE
Update ShortTimeFormatter.cs

### PR DESCRIPTION
**Pull request by 10-days-till-xmas**
Allows for 3 decimal places for use in components

### CODE REVIEW

**Comment by wooferzfg** [comment]
This change affects more than just components - it updates the default value to milliseconds

**Comment by wooferzfg** [comment]
Why can't a component just use `GeneralTimeFormatter`?

**Comment by 10-days-till-xmas** [comment]
ah i didnt know abt  `GeneralTimeFormatter`, I'll use that instead

**Comment by 10-days-till-xmas** [comment]
Would it be okay to make a new `MillisecondTimeFormatter` file instead

**Comment by wooferzfg** [comment]
You shouldn't need that for the implementation. All the components with an accuracy setting already pass it to the time formatter, instead of using a hardcoded accuracy value.

**Pull request closed without merging**
