### PR TITLE
Add `.editorconfig` & apply style rules

### PR DESCRIPTION
**Pull request by just-ero**
### Description

* Introduces an `.editorconfig` file to enforce consistent style rules across LiveSplit projects.
* Upgrades the language version to C# 12 (most recent stable).
* Adds `PolySharp` to all projects to allow for support of some language features which require runtime support (`Index` & `Range` operators).
* Fixes some warnings.

### CODE REVIEW

**Comment by wooferzfg** [comment]
Why did the deep pointer tests need to change?

**Comment by wooferzfg** [comment]
Can we exclude `LiveSplitCore.cs`?

Screenshot_20240902_103834_Chrome Beta

**Comment by wooferzfg** [comment]
Why are there still some build warnings?

**Comment by just-ero** [comment]
`DeepPointer.InitializeOffsets` now uses a collection initializer instead of `List<T>.AddRange`. Passing a `null` collection to `AddRange` causes `ArgumentNullException`. Passing a `null` collection into a collection initializer causes `NullReferenceException`.

**Comment by just-ero** [comment]
We cannot exclude `LiveSplitCore.cs` this way.

**Comment by wooferzfg** [comment]
If we're not fixing them, can we suppress the warnings in these particular spots so that they don't show up in the CI build?

**Comment by wooferzfg** [comment]
> We cannot exclude `LiveSplitCore.cs` this way.

Maybe filter the warnings in GitHub Actions then? We need some way to keep the build output clean

**Comment by just-ero** [comment]
We can rename the file from `LiveSplitCore.cs` to `LiveSplitCore.g.cs`. This also indicates that the code is generated and excludes it from analysis.

**Comment by wooferzfg** [comment]
> We can rename the file from `LiveSplitCore.cs` to `LiveSplitCore.g.cs`. This also indicates that the code is generated and excludes it from analysis.

That works

**Pull request merged**
