### PR TITLE
IntPtr.ToInt32 will throw an OverflowException if it's < 0.

### PR DESCRIPTION
**Pull request by zzymyn**
#416

### CODE REVIEW

**Comment by zzymyn** [comment]
See https://github.com/dotnet/coreclr/blob/master/src/mscorlib/src/System/IntPtr.cs#L115 for IntPtr.ToInt32 code.

**Comment by wooferzfg** [comment]
It's a signed integer, though. IntPtr.ToInt32 should only throw an exception if the number's magnitude is too large to be represented with 32 bits.

**Comment by zzymyn** [comment]
Hmm yes that's true. I could have sworn I'd had this happen but can't get it to happen again even with the original code now...

**Comment by wooferzfg** [comment]
Does it maybe have to do with the OS?

**Comment by zzymyn** [comment]
Maybe running on a 32-bit Windows? Expansion of the lparam from 32 bits to 64 bits?

**Comment by wooferzfg** [comment]
The person in the tweet in #416 said they were on 64-bit though...

**Comment by zzymyn** [comment]
Right. I will investigate further.

**Pull request closed without merging**
