### PR TITLE
Added C&C: Yuri's Revenge to Auto-splitter list

### PR DESCRIPTION
**Pull request by ROMaster2**

### CODE REVIEW

**Comment by wooferzfg** [comment]
you need to escape the & character

**Comment by 0Seren** [comment]
To escape `&` in XML replace it with `&amp;` not `\&`

**Comment by ROMaster2** [comment]
Give me literally one minute and I would have figured that out

**Comment by wooferzfg** [comment]
sorry i didn't clarify - you need to use &amp; instead of & or \&

**Comment by blastedt** [comment]
Hey you should think about escaping the ampersand characters with the HTML escape code &amp;.

**Pull request merged**
