### PR TITLE
Update LiveSplit.AutoSplitters.xml

### PR DESCRIPTION
**Pull request by VeritasDL**
added SADX autosplitter

### CODE REVIEW

**Comment by wooferzfg1** [comment]
For next time:

LiveSplit automatically makes game names lowercase so capitalization
doesn't matter (SADX and sadx are identical) and we can't add two games
with the same key, so I removed "sadx" from the XML.

**Comment by CryZe** [comment]
Gotta love the unit tests :D

**Comment by wooferzfg1** [comment]
Yeah, it's very cool. There's no way I would've noticed that something was wrong otherwise

**Comment by VeritasDL** [comment]
Okay thanks,

**Pull request merged**
