### PR TITLE
Add System Shock 2 autosplitter

### PR DESCRIPTION
**Pull request by IndelibleRaven**

### CODE REVIEW

**Comment by fatalis** [comment]
uhh

**Comment by IndelibleRaven** [comment]
I apologize for anything dodgy going on. I haven't worked with GitHub in years.

**Comment by fatalis** [comment]
you have to add a new entry, you can't replace someone elses

**Comment by IndelibleRaven** [comment]
I didn't even realize I was doing that. My apologies! Do I make a new pull request or can I fix this one?

**Comment by fatalis** [comment]
easier to make a new one

**Comment by fatalis** [comment]
f

**Comment by IndelibleRaven** [comment]
Will do. Thank you!

**Pull request closed without merging**
