### PR TITLE
Added a couple game names for Bioshock Infinite

### PR DESCRIPTION
**Pull request by Dread2472**

### CODE REVIEW

**Comment by CryZe** [comment]
LiveSplit 1.6 is case insensitive, while 1.5 isn't. I advise against adding special cases for the casing. You should probably just wait for 1.6, which we hope to release soon anyway.

**Comment by Dread2472** [comment]
Well can you change them to the upper-case S versions, then

**Comment by CryZe** [comment]
You don't need to close Pull Requests to edit them btw.

**Comment by wooferzfg1** [comment]
https://github.com/LiveSplit/LiveSplit/commit/fafed6af9e7470108d7eb962be8babc9183f3711 fixed

**Pull request closed without merging**
