### PR TITLE
Add Final Fantasy X to Autosplitter

### PR DESCRIPTION
**Pull request by flobberworm4**
Final Fantasy X Component containing Auto Start/Reset, Load Removal, and an additional component for an Encounter Count. By Psychonauter and Flobberworm4.

### CODE REVIEW

**Comment by CryZe** [comment]
Can you amend / rebase / ... that commit? It seems like the CI has some weird problems.

**Comment by flobberworm4** [comment]
Reattempted it now, seems to have passed (sorry, complete newb to Github)

**Comment by wooferzfg** [comment]
don't you want "Show In Layout Editor" for the UI?

**Comment by wooferzfg** [comment]
actually maybe not

**Comment by flobberworm4** [comment]
Ah ha, I removed it because wasn't sure if it was needed, added back in now, not sure what is required for the Encounter Count component to show in the layout editor

**Comment by wooferzfg** [comment]
OK you don't need it because you have 2 separate dll's in the URLs. sorry =p

**Comment by flobberworm4** [comment]
Haha no worries, I'll remove and rebuild

**Pull request merged**
