### PR TITLE
Add New Vegas to Autosplitters XML

### PR DESCRIPTION
**Pull request by drtchops**
I remembered to set it as a Script this time

### CODE REVIEW

**Comment by CryZe** [comment]
Don't worry, we have automated Unit Tests for the Auto Splitters XML now :smile:

**Comment by drtchops** [comment]
But no documentation > : (

**Comment by CryZe** [comment]
Don't worry, it's already half done. I'll finish it today I think.

**Comment by drtchops** [comment]
dude nice, I should've bugged you about that awhile ago

**Pull request merged**
