### PR TITLE
Updated the Dark Souls 1 In-Game Timer

### PR DESCRIPTION
**Pull request by CapitaineToinon**
Update of the In-Game Timer for Dark Souls 1 :
https://github.com/CapitaineToinon/LiveSplit.DarkSoulsIGT

### CODE REVIEW

**Comment by wooferzfg** [comment]
Please escape the & in the description or replace it with "and".

**Comment by CapitaineToinon** [comment]
Actually before I change that, will the old dll be replaced automatically by the new one from the componant folder? Maybe I should just keep the same name for the dll then. Sorry I'm not familliar with how the autosplitters are loaded.

**Comment by wooferzfg** [comment]
Yes, it'll overwrite the file.

**Comment by CapitaineToinon** [comment]
Sorry I'm a bit confused, am I supposed to make a new pull requests? I thought I could commit on pull requests like on a branch but it doesn't apear in the list of requests in github desktop. The only [link](https://github.com/LiveSplit/LiveSplit/blob/438096c868abe51e72891ccc9b351792d8b7ef18/LiveSplit.AutoSplitters.xml) I have doesn't allow me to edit it.

**Pull request closed without merging**
