### PR TITLE
Add a button to go to an autosplitter's website

### LINKED ISSUE #23: Suggestion: Open autosplitter website button
_From @fatalis on September 2, 2014 2:50_

Suggestion: Add a button here that will open up the auto-splitter's website. Get the url from AutoSplitters.xml.

It's a pain in the ass to create a settings form with just one button just to open up my component's docs.

jwapdbn

_Copied from original issue: LiveSplit/LiveSplitIssues#22_

### PR DESCRIPTION
**Pull request by fatalis**
People don't know where to go to get support, this solves that

Resolves #23

### CODE REVIEW

**Comment by fatalis** [comment]
The button is only visible when the autosplitter xml entry contains the website node.

**Comment by CryZe** [comment]
Can you post a screenshot of how the Run Editor looks like with the button? I'm not home yet, so I can't check.

**Comment by fatalis** [comment]
view when autosplitter doesnt have a website defined http://i.imgur.com/ZN6IGmy.png
website defined http://i.imgur.com/0bRoA97.png

**Comment by CryZe** [comment]
It also maybe might make sense for there to be a name attribute for customizing the text on the button?

<Website name="@CryZe107">https://twitter.com/CryZe107"</Website> for example

**Comment by CryZe** [comment]
Also idk how well this handles long description texts. Maybe we should have a
```xml
<Author name="CryZe">https://twitter.com/CryZe107</Author>
```
instead and show that as a clickable Label, instead of having the Author in the parenthesis of the description.

**Comment by fatalis** [comment]
Long description fields wrap to next line. An author link isn't good enough, it needs to be the documentation of the autosplitter. I don't want to answer twitter questions all the time for stuff that's been written elsewhere already.

**Comment by fatalis** [comment]
Looked into implementing the author stuff, but there are a couple issues due to format change of the xml and I think you guys should be the ones to figure that out.

**Comment by CryZe** [comment]
I merged it in like it was. I guess we can do more changes to it later on if we want to.

**Pull request merged**
