### PR TITLE
Twitter authorization modification

### PR DESCRIPTION
**Pull request by Seldszar**
Twitter share now use PIN authentication and fix Twitter sharing issue (#121).

### CODE REVIEW

**Comment by CryZe** [comment]
This was already fixed in master. I don't see a point in deleting the whole OAuth Form :confused:

**Comment by CryZe** [comment]
Wait what, looks like it was not fixed on master. Maybe some other branch? I remember fixing it.

**Comment by wooferzfg1** [comment]
I never saw you fix it; I only saw you make the issue

**Comment by CryZe** [comment]
I just fixed it: https://github.com/CryZe/LiveSplit/commit/9d62a2a733ae1c9f0fcf8e4d35ac60c092563e33

**Comment by CryZe** [comment]
Sorry that you put quite some effort in this, but the solution was way simpler than deleting pretty much everything. I liked a few clean ups you did, so I guess you can do a Pull Request with those if you want. I don't want to get rid of the OAuth Form itself though, since having to copy paste a PIN around is just way worse for the user.

**Pull request closed without merging**
